[supervisord]
; Exécuter Supervisor au premier plan (utile en conteneur)
nodaemon=true

[program:front]
; Serveur web du front (Caddy)
command = /usr/sbin/caddy run
autostart = true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:back]
; API Spring Boot
command = /usr/bin/java -jar /app/back/microcrm-0.0.1-SNAPSHOT.jar
autostart = true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[unix_http_server]
; Socket local Supervisor
file=/var/run/supervisor.sock

[rpcinterface:supervisor]
; Interface RPC de Supervisor
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface